const FormSchema = {
    "adjustTotal": 0,
    "applyTime": "",
    "auditStatus": 0,
    "bizKey": "",
    "bizPriority": "",
    "callType": "",
    "camundaProcdefId": "",
    "camundaProcdefKey": "",
    "camundaProcinsId": "",
    "camundaTaskId": "",
    "closingExplanation": "",
    "closingStock": 0,
    "closingStockTotal": 0,
    "createUserId": 0,
    "createUserParentDeptId": 0,
    "createUserParentOrgId": 0,
    "explanation": "",
    "fillTime": "",
    "id": 0,
    "incrExplanation": "",
    "isChange": false,
    "nglstockIncrTotal": 0,
    "openingExplanation": "",
    "openingStock": 0,
    "openingStockTotal": 0,
    "procdefName": "",
    "procdefTypeId": 0,
    "procdefTypeName": "",
    "procdefVersion": 0,
    "processName": "",
    "projectCode": "",
    "projectList": [
      {
        "applyTime": "",
        "auditStatus": 0,
        "bizKey": "",
        "bizPriority": "",
        "callType": "",
        "camundaProcdefId": "",
        "camundaProcdefKey": "",
        "camundaProcinsId": "",
        "camundaTaskId": "",
        "clientId": 0,
        "createUserId": 0,
        "createUserParentDeptId": 0,
        "createUserParentOrgId": 0,
        "goodsId": 0,
        "id": 0,
        "isChange": false,
        "procdefName": "",
        "procdefTypeId": 0,
        "procdefTypeName": "",
        "procdefVersion": 0,
        "processName": "",
        "projectCode": "",
        "projectName": "",
        "reason": ""
      }
    ],
    "projectName": "",
    "reason": "",
    "salesTotal": 0,
    "selfUse": 0,
    "smmHebooilGoodsAdjustList": [
      {
        "applyTime": "",
        "auditStatus": 0,
        "bizKey": "",
        "bizPriority": "",
        "callType": "",
        "camundaProcdefId": "",
        "camundaProcdefKey": "",
        "camundaProcinsId": "",
        "camundaTaskId": "",
        "clientCode": "",
        "clientName": "",
        "createUserId": 0,
        "createUserParentDeptId": 0,
        "createUserParentOrgId": 0,
        "explanation": "",
        "goodsId": 0,
        "goodsNumber": 0,
        "id": 0,
        "isChange": false,
        "procdefName": "",
        "procdefTypeId": 0,
        "procdefTypeName": "",
        "procdefVersion": 0,
        "processName": "",
        "projectCode": "",
        "projectName": "",
        "reason": ""
      }
    ],
    "smmHebooilGoodsClosingList": [
      {
        "applyTime": "",
        "auditStatus": 0,
        "bizKey": "",
        "bizPriority": "",
        "callType": "",
        "camundaProcdefId": "",
        "camundaProcdefKey": "",
        "camundaProcinsId": "",
        "camundaTaskId": "",
        "closingStock": 0,
        "createUserId": 0,
        "createUserParentDeptId": 0,
        "createUserParentOrgId": 0,
        "explanation": "",
        "goodsId": 0,
        "id": 0,
        "isChange": false,
        "procdefName": "",
        "procdefTypeId": 0,
        "procdefTypeName": "",
        "procdefVersion": 0,
        "processName": "",
        "reason": "",
        "spreadClosingStock": 0
      }
    ],
    "smmHebooilGoodsNglstockList": [
      {
        "applyTime": "",
        "auditStatus": 0,
        "bizKey": "",
        "bizPriority": "",
        "callType": "",
        "camundaProcdefId": "",
        "camundaProcdefKey": "",
        "camundaProcinsId": "",
        "camundaTaskId": "",
        "clientCode": "",
        "clientName": "",
        "createUserId": 0,
        "createUserParentDeptId": 0,
        "createUserParentOrgId": 0,
        "explanation": "",
        "goodsId": 0,
        "goodsNumber": 0,
        "id": 0,
        "isChange": false,
        "procdefName": "",
        "procdefTypeId": 0,
        "procdefTypeName": "",
        "procdefVersion": 0,
        "processName": "",
        "projectCode": "",
        "projectName": "",
        "reason": ""
      }
    ],
    "smmHebooilGoodsOpeningList": [
      {
        "applyTime": "",
        "auditStatus": 0,
        "bizKey": "",
        "bizPriority": "",
        "callType": "",
        "camundaProcdefId": "",
        "camundaProcdefKey": "",
        "camundaProcinsId": "",
        "camundaTaskId": "",
        "createUserId": 0,
        "createUserParentDeptId": 0,
        "createUserParentOrgId": 0,
        "explanation": "",
        "goodsId": 0,
        "id": 0,
        "isChange": false,
        "openingStock": 0,
        "procdefName": "",
        "procdefTypeId": 0,
        "procdefTypeName": "",
        "procdefVersion": 0,
        "processName": "",
        "reason": "",
        "spreadOpeningStock": 0
      }
    ],
    "smmHebooilGoodsSalesList": [
      {
        "applyTime": "",
        "auditStatus": 0,
        "bizKey": "",
        "bizPriority": "",
        "callType": "",
        "camundaProcdefId": "",
        "camundaProcdefKey": "",
        "camundaProcinsId": "",
        "camundaTaskId": "",
        "clientCode": "",
        "clientName": "",
        "createUserId": 0,
        "createUserParentDeptId": 0,
        "createUserParentOrgId": 0,
        "explanation": "",
        "goodsId": 0,
        "goodsNumber": 0,
        "id": 0,
        "isChange": false,
        "procdefName": "",
        "procdefTypeId": 0,
        "procdefTypeName": "",
        "procdefVersion": 0,
        "processName": "",
        "projectCode": "",
        "projectName": "",
        "reason": ""
      }
    ],
    "smmHebooilGoodsSelfList": [
      {
        "applyTime": "",
        "auditStatus": 0,
        "bizKey": "",
        "bizPriority": "",
        "callType": "",
        "camundaProcdefId": "",
        "camundaProcdefKey": "",
        "camundaProcinsId": "",
        "camundaTaskId": "",
        "clientCode": "",
        "clientName": "",
        "createUserId": 0,
        "createUserParentDeptId": 0,
        "createUserParentOrgId": 0,
        "explanation": "",
        "goodsId": 0,
        "goodsNumber": 0,
        "id": 0,
        "isChange": false,
        "procdefName": "",
        "procdefTypeId": 0,
        "procdefTypeName": "",
        "procdefVersion": 0,
        "processName": "",
        "projectCode": "",
        "projectName": "",
        "reason": ""
      }
    ],
    "smmHebooilGoodsStockList": [
      {
        "applyTime": "",
        "auditStatus": 0,
        "bizKey": "",
        "bizPriority": "",
        "callType": "",
        "camundaProcdefId": "",
        "camundaProcdefKey": "",
        "camundaProcinsId": "",
        "camundaTaskId": "",
        "createUserId": 0,
        "createUserParentDeptId": 0,
        "createUserParentOrgId": 0,
        "explanation": "",
        "goodsId": 0,
        "id": 0,
        "isChange": false,
        "procdefName": "",
        "procdefTypeId": 0,
        "procdefTypeName": "",
        "procdefVersion": 0,
        "processName": "",
        "reason": "",
        "spreadStockIncr": 0,
        "stockIncr": 0
      }
    ],
    "spreadClosingStock": 0,
    "spreadOpeningStock": 0,
    "spreadStockIncr": 0,
    "stockIncr": 0,
    "stockIncrTotal": 0,
    "titleName": ""
  }

// export type {
//     FormType
// }

export {
    FormSchema
}